// SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and jdklogs contributors
// SPDX-License-Identifier: GPL-2.0-only

/** XML-escape a string for use in an attribute value or text node. */
function esc(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

/**
 * Build a JFR `.jfc` configuration enabling exactly the given events. The shape mirrors a real
 * JDK-25 `default.jfc`: `<configuration version="2.0">` with one `<event>` per event, each carrying
 * an `enabled=true` setting. A leading comment records the caveat that an event only takes effect if
 * it actually exists in the target JDK (this mapping is derived from JDK 25).
 */
export function buildJfc(events: string[], opts?: { label?: string; description?: string }): string {
  const uniq = [...new Set(events)].sort();
  const label = opts?.label ?? "jdklogs JFR selection";
  const description =
    opts?.description ??
    "Events reflecting the JDK-25 log→JFR mapping. An event only takes effect if it exists in your target JDK.";

  const lines: string[] = [];
  lines.push(`<?xml version="1.0" encoding="UTF-8"?>`);
  lines.push(
    `<!-- Generated by jdklogs. Events reflect the JDK-25 log→JFR mapping; an event takes ` +
      `effect only if it exists in your target JDK. -->`
  );
  lines.push(`<configuration version="2.0" label="${esc(label)}" description="${esc(description)}">`);
  for (const e of uniq) {
    lines.push(`  <event name="${esc(e)}">`);
    lines.push(`    <setting name="enabled">true</setting>`);
    lines.push(`  </event>`);
  }
  lines.push(`</configuration>`);
  return lines.join("\n") + "\n";
}

/** Trigger a client-side download of a `.jfc` for the given events. */
export function triggerJfcDownload(
  events: string[],
  filename: string,
  opts?: { label?: string; description?: string }
): void {
  const xml = buildJfc(events, opts);
  const blob = new Blob([xml], { type: "application/xml" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
