// SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and jdklogs contributors
// SPDX-License-Identifier: GPL-2.0-only
package me.bechberger.jdklogs

/**
 * Self-authored one-line descriptions for every HotSpot log tag (from `logTag.hpp`).
 *
 * These feed the frontend's selector wizard so a user can understand what each tag covers without
 * reading the source. Descriptions are hand-written best-effort summaries, not authoritative JDK
 * documentation. Unknown/future tags fall back to a generic message.
 */
object TagDescriptions {
    private val MAP: Map<String, String> = mapOf(
        "add" to "Adding entries to internal tables or collections.",
        "age" to "Object aging and tenuring distribution during GC.",
        "alloc" to "Memory allocation activity.",
        "annotation" to "Java annotation processing in the VM.",
        "aot" to "Ahead-of-time compilation and the AOT cache.",
        "arguments" to "JVM command-line argument parsing and processing.",
        "array" to "Array-related operations in the VM.",
        "asan" to "AddressSanitizer instrumentation events.",
        "attach" to "Dynamic attach API (tools attaching to a running VM).",
        "barrier" to "GC read/write barrier activity.",
        "blocks" to "Block-level bookkeeping in the collector or code cache.",
        "bot" to "Block-offset table maintenance for the heap.",
        "breakpoint" to "Debugger breakpoint handling.",
        "bytecode" to "Bytecode-level events and processing.",
        "cause" to "The cause that triggered an operation (e.g. GC cause).",
        "cds" to "Class Data Sharing archive load/dump.",
        "census" to "Object/region census statistics during GC.",
        "class" to "Class loading, linking and lifecycle.",
        "classhisto" to "Class histogram generation (object counts per class).",
        "cleanup" to "Cleanup phases and deferred resource reclamation.",
        "codecache" to "JIT-compiled code cache management.",
        "codestrings" to "Debug strings embedded in generated code.",
        "compaction" to "Heap compaction during GC.",
        "compilation" to "JIT compilation events.",
        "condy" to "Dynamic constant (constant-dynamic / condy) resolution.",
        "constantpool" to "Constant pool resolution and caching.",
        "constraints" to "Argument/flag constraint checking.",
        "container" to "Container (cgroup) detection and resource limits.",
        "continuations" to "Virtual thread continuations (mounting/unmounting).",
        "coops" to "Compressed ordinary object pointers configuration.",
        "cpu" to "CPU detection and time accounting.",
        "cset" to "GC collection set selection.",
        "data" to "Generic data-structure bookkeeping.",
        "datacreation" to "Creation of internal data structures.",
        "dcmd" to "Diagnostic command (jcmd) execution.",
        "deathtest" to "Internal death-test harness output.",
        "decoder" to "Native stack/symbol decoding.",
        "defaultmethods" to "Interface default-method resolution.",
        "deoptimization" to "Deoptimization of compiled frames.",
        "dependencies" to "Compiler dependency tracking and invalidation.",
        "director" to "GC director / heuristics driving collection decisions.",
        "downcall" to "Foreign Function & Memory downcalls (Java → native).",
        "dump" to "Heap/archive dump operations.",
        "dynamic" to "Dynamic CDS archive operations.",
        "ergo" to "Ergonomic (automatic) tuning decisions.",
        "event" to "Internal VM event dispatch.",
        "exceptions" to "Exception creation and dispatch in the VM.",
        "exit" to "VM shutdown and exit handling.",
        "fastlock" to "Fast-path monitor (lock) operations.",
        "finalizer" to "Object finalization processing.",
        "fingerprint" to "Method/class fingerprinting.",
        "foreign" to "Foreign Function & Memory API activity.",
        "free" to "Freeing of memory or resources.",
        "freelist" to "Free-list management for the heap.",
        "gc" to "Garbage collection (the umbrella GC tag).",
        "generate" to "Code or data generation steps.",
        "generateoopmap" to "Generation of oop maps for methods.",
        "handshake" to "Thread handshakes (per-thread safepoint-like ops).",
        "hashtables" to "Internal hashtable operations.",
        "heap" to "Java heap sizing and state.",
        "heapdump" to "Heap dump generation.",
        "heapsampling" to "Low-overhead heap allocation sampling.",
        "hotcode" to "Hot-code detection and placement.",
        "humongous" to "Humongous (very large) object handling in G1.",
        "ihop" to "G1 Initiating Heap Occupancy Percent heuristics.",
        "iklass" to "InstanceKlass metadata operations.",
        "indy" to "invokedynamic call-site resolution.",
        "init" to "VM initialization steps.",
        "inlinecache" to "Inline cache setup and clearing.",
        "inlining" to "Compiler method inlining decisions.",
        "install" to "Installation of compiled code or data.",
        "interpreter" to "Bytecode interpreter events.",
        "itables" to "Interface method table (itable) construction.",
        "jfr" to "JDK Flight Recorder internals.",
        "jit" to "Just-in-time compiler activity.",
        "jmethod" to "jmethodID lifecycle.",
        "jni" to "Java Native Interface calls and handles.",
        "jvmti" to "JVM Tool Interface (JVMTI) events.",
        "lambda" to "Lambda metafactory and lambda-form handling.",
        "library" to "Native library loading.",
        "link" to "Class/method linking.",
        "liveness" to "Object liveness analysis during GC.",
        "load" to "Class or resource loading.",
        "loader" to "Class loader activity and hierarchies.",
        "logging" to "The logging subsystem itself.",
        "malloc" to "Native malloc/free accounting (NMT).",
        "map" to "Memory mapping operations.",
        "mark" to "GC marking phase.",
        "marking" to "GC concurrent/parallel marking details.",
        "membername" to "MemberName resolution for method handles.",
        "memops" to "Low-level memory operations.",
        "metadata" to "Class metadata (metaspace) management.",
        "metaspace" to "Metaspace allocation and sizing.",
        "methodcomparator" to "Method comparison during redefinition.",
        "methodhandles" to "MethodHandle creation and resolution.",
        "methodtrace" to "Per-method entry/exit tracing.",
        "mirror" to "java.lang.Class mirror handling.",
        "mmu" to "Minimum mutator utilization (GC pause budgeting).",
        "module" to "Java module system operations.",
        "monitorinflation" to "Object monitor inflation (lock → heavyweight).",
        "monitormismatch" to "Monitor enter/exit mismatch detection.",
        "name" to "Symbol/name resolution.",
        "native" to "Native code interactions.",
        "nestmates" to "Nest-based access control (nestmates).",
        "nmethod" to "Compiled method (nmethod) lifecycle.",
        "nmt" to "Native Memory Tracking.",
        "normalize" to "Path/name normalization.",
        "numa" to "NUMA-aware allocation and topology.",
        "objecttagging" to "JVMTI object tagging.",
        "obsolete" to "Obsolete/deprecated method handling on redefinition.",
        "oldobject" to "Old-object sampling (JFR leak profiling).",
        "oom" to "Out-of-memory handling.",
        "oopmap" to "Oop map construction and lookup.",
        "oops" to "Ordinary object pointer operations.",
        "oopstorage" to "OopStorage (VM-managed oop handles) management.",
        "os" to "Operating-system interaction.",
        "owner" to "Lock/monitor ownership tracking.",
        "package" to "Java package definition and lookup.",
        "page" to "Memory page operations.",
        "pagesize" to "Page-size selection (including large pages).",
        "parser" to "Parsing of files or descriptors.",
        "patch" to "Runtime code patching.",
        "path" to "Class path / module path processing.",
        "perf" to "Performance counters (perfdata).",
        "periodic" to "Periodic tasks scheduled by the VM.",
        "phases" to "Phase-level timing breakdown of an operation.",
        "plab" to "Promotion Local Allocation Buffers during GC.",
        "placeholders" to "Class-loading placeholder tracking.",
        "preempt" to "Virtual-thread preemption.",
        "preload" to "Class preloading (AOT/CDS).",
        "preorder" to "Class-init preorder processing.",
        "preview" to "Preview-feature gating.",
        "promotion" to "Object promotion between GC generations.",
        "ptrqueue" to "Pointer queues used by GC barriers.",
        "purge" to "Purging of stale metadata or entries.",
        "record" to "Java record component handling.",
        "redact" to "Redaction of sensitive output.",
        "redefine" to "Class redefinition/retransformation (JVMTI).",
        "ref" to "Reference (soft/weak/phantom) processing.",
        "refine" to "G1 concurrent refinement of remembered sets.",
        "region" to "Heap region management (G1/Shenandoah/ZGC).",
        "reloc" to "Relocation of compiled-code addresses.",
        "relocator" to "Bytecode relocator during instrumentation.",
        "remset" to "Remembered-set maintenance.",
        "resolve" to "Symbolic reference resolution.",
        "safepoint" to "Safepoint synchronization.",
        "sampling" to "General sampling activity.",
        "scavenge" to "Young-generation scavenging.",
        "sealed" to "Sealed-class permitted-subclass checks.",
        "setting" to "Configuration/setting changes.",
        "smr" to "Safe Memory Reclamation for thread lists.",
        "stackbarrier" to "Stack watermark barriers (concurrent stack scanning).",
        "stackmap" to "Stack map table processing for verification.",
        "stacktrace" to "Stack trace capture.",
        "stackwalk" to "Stack walking.",
        "start" to "Start of an operation or subsystem.",
        "startup" to "VM startup sequence.",
        "startuptime" to "Timing of startup phases.",
        "state" to "State transitions of VM components.",
        "stats" to "Statistics reporting.",
        "streaming" to "JFR event streaming.",
        "stringdedup" to "String deduplication during GC.",
        "stringtable" to "Interned string table management.",
        "stubs" to "Generated stub routines.",
        "subclass" to "Subclass relationship tracking.",
        "survivor" to "Survivor space sizing during GC.",
        "suspend" to "Thread suspend/resume.",
        "sweep" to "Code-cache sweeping.",
        "symboltable" to "Symbol table management.",
        "system" to "System-level VM operations.",
        "table" to "Generic internal table operations.",
        "task" to "Task scheduling and execution.",
        "test" to "Internal test-only logging.",
        "thread" to "Thread lifecycle and management.",
        "throttle" to "Rate throttling of an activity.",
        "timer" to "Timer and timing operations.",
        "tlab" to "Thread-Local Allocation Buffers.",
        "tracking" to "Resource tracking (e.g. native memory).",
        "training" to "Training-run data capture for AOT/CDS.",
        "trimnative" to "Trimming native (glibc) heap back to the OS.",
        "unload" to "Class unloading.",
        "unmap" to "Unmapping of memory regions.",
        "unshareable" to "Restoring unshareable state from a CDS archive.",
        "upcall" to "Foreign Function & Memory upcalls (native → Java).",
        "update" to "Updating internal structures.",
        "valuebasedclasses" to "Value-based class misuse warnings (e.g. synchronizing on them).",
        "valuetypes" to "Value-type (Valhalla) handling.",
        "verification" to "Bytecode verification.",
        "verify" to "Internal consistency verification (e.g. heap verify).",
        "vmatree" to "Virtual-memory region tree (NMT) operations.",
        "vmmutex" to "VM-internal mutex/lock activity.",
        "vmoperation" to "VM operations executed at a safepoint.",
        "vmthread" to "The VM thread and its operation queue.",
        "vtables" to "Virtual method table (vtable) construction.",
        "vtablestubs" to "Generated vtable stub routines."
    )

    fun describe(tag: String): String =
        MAP[tag] ?: "HotSpot log tag \"$tag\"."
}
